name: Hello GH Actions

on:
  push:
    branches:
      - main

jobs:
  hello-gh-action:
    name: "hello gh action"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ls repository
        run:  ls  
