name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "publish to ghpages"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup git config
        run: git config user.email "shinpeim@gmail.com" && git config user.name "Shinpei Maruyama"
      - name: publish
        run:  bash ./publish.sh
