name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "publish to ghpages"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish
        run:  bash ./publish.sh
